name: CD Pipeline bloggy app
on:
    push:
        branches: ['main']
    
build-and-push:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: swapnadip98/blog-app
            IMAGE_TAG: build-${{github.run_number}} #swapnadip98/blog-app:build-1
            
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v4
            - name: Build docker image
              run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 .
            - name: Login into Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}
            - name: Push docker image to Docker Hub
              run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
